const cfg=window.JULIETE_CONFIG||{},dialog=document.querySelector("#booking-dialog"),form=document.querySelector("#booking-form"),errorBox=document.querySelector(".form-error");
let step=1,services=[],lastBooking=null;
const api=async(path,body)=>{const r=await fetch(cfg.supabaseUrl+"/rest/v1/"+path,{method:"POST",headers:{apikey:cfg.supabaseKey,Authorization:"Bearer "+cfg.supabaseKey,"Content-Type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json().catch(()=>({}))).message||"Não foi possível salvar.");return r.status===204?null:r.json()};
const track=(name,data={})=>api("rpc/ingest_site_event",{p_site_key:cfg.siteKey,p_event_name:name,p_session_id:sessionStorage.jgSession||(sessionStorage.jgSession=crypto.randomUUID()),p_page_path:location.pathname,p_metadata:data,p_occurred_at:new Date().toISOString()}).catch(()=>{});
function renderServices(){const names=services.length?services:cfg.fallbackServices.map((name,i)=>({id:"fallback-"+i,name}));document.querySelector("#service-grid").innerHTML=names.slice(0,6).map((s,i)=>`<article class="service-card reveal"><span>${["✦","✂","♡","◌","❋","◇"][i%6]}</span><h3>${s.name}</h3><p>Atendimento personalizado e cuidadoso para o bem-estar do seu pet.</p><button data-service="${s.id}">Agendar este serviço →</button></article>`).join("");document.querySelector("#service-options").innerHTML=names.map(s=>`<label class="service-option"><input type="radio" name="service_id" value="${s.id}" data-name="${s.name}" required><span><i>✦</i><b>${s.name}</b><small>Selecionar</small></span></label>`).join("");document.querySelectorAll("[data-service]").forEach(b=>b.onclick=()=>openBooking(b.dataset.service))}
async function loadServices(){try{const r=await fetch(cfg.supabaseUrl+"/rest/v1/services?select=id,name&organization_id=eq.7781d977-ce92-438e-ac45-de01a9247742&active=eq.true&order=name",{headers:{apikey:cfg.supabaseKey,Authorization:"Bearer "+cfg.supabaseKey}});if(r.ok)services=await r.json()}catch{}renderServices()}
function setStep(n){step=n;document.querySelectorAll(".form-step").forEach(x=>x.classList.toggle("active",+x.dataset.step===n));document.querySelectorAll(".steps span").forEach((x,i)=>x.classList.toggle("active",i<n));document.querySelectorAll(".steps b").forEach((x,i)=>x.classList.toggle("active",i<n-1));document.querySelector("#back-step").style.visibility=n===1?"hidden":"visible";document.querySelector("#next-step").hidden=n===4;document.querySelector("#submit-booking").hidden=n!==4;if(n===4)review();dialog.querySelector(".modal-shell").scrollTo({top:0,behavior:"smooth"});track("booking_step_view",{step:n})}
function openBooking(serviceId){form.hidden=false;document.querySelector("#booking-success").classList.remove("active");errorBox.textContent="";form.reset();if(serviceId){const input=form.querySelector(`[value="${CSS.escape(serviceId)}"]`);if(input)input.checked=true}const tomorrow=new Date(Date.now()+864e5).toISOString().slice(0,10);form.date.min=tomorrow;form.date.value=tomorrow;setStep(serviceId?2:1);dialog.showModal();document.body.classList.add("modal-open");track("booking_open",{service_id:serviceId||null})}
function closeBooking(){dialog.close();document.body.classList.remove("modal-open")}
function validStep(){const fields=[...document.querySelector(`.form-step[data-step="${step}"]`).querySelectorAll("input,select,textarea")];for(const field of fields)if(!field.checkValidity()){field.reportValidity();return false}return true}
function values(){const fd=new FormData(form),service=form.querySelector("[name=service_id]:checked");return Object.fromEntries([...fd.entries()].concat([["service_name",service?.dataset.name||"Serviço"]]))}
function review(){const v=values(),date=v.date?new Date(v.date+"T12:00:00").toLocaleDateString("pt-BR"):"";document.querySelector("#booking-review").innerHTML=`<div><small>Serviço</small><b>${v.service_name}</b></div><div><small>Pet</small><b>${v.pet_name} · ${v.species}</b></div><div><small>Responsável</small><b>${v.owner_name}</b></div><div><small>Data preferida</small><b>${date} às ${v.time}</b></div><div><small>WhatsApp</small><b>${v.phone}</b></div>`}
document.querySelectorAll("[data-open-booking]").forEach(b=>b.onclick=()=>openBooking());document.querySelectorAll("[data-close]").forEach(b=>b.onclick=closeBooking);dialog.addEventListener("click",e=>{if(e.target===dialog)closeBooking()});
document.querySelector("#next-step").onclick=()=>{errorBox.textContent="";if(validStep())setStep(step+1)};document.querySelector("#back-step").onclick=()=>setStep(step-1);
form.phone.addEventListener("input",e=>{let v=e.target.value.replace(/\D/g,"").slice(0,11);e.target.value=v.replace(/^(\d{2})(\d)/,"($1) $2").replace(/(\d{5})(\d{4})$/,"$1-$2")});
form.addEventListener("input",()=>{const v=values();localStorage.setItem("julieteBookingDraft",JSON.stringify(v))});
form.onsubmit=async e=>{e.preventDefault();if(!validStep())return;const v=values(),submit=document.querySelector("#submit-booking"),session=sessionStorage.jgSession||(sessionStorage.jgSession=crypto.randomUUID());submit.disabled=true;submit.textContent="Salvando…";errorBox.textContent="";try{const scheduled=new Date(v.date+"T"+v.time+":00-03:00").toISOString();const result=await api("rpc/submit_pet_booking",{p_site_key:cfg.siteKey,p_session_id:session,p_responsible_name:v.owner_name,p_phone:v.phone,p_pet:{name:v.pet_name,species:v.species,breed:v.breed||null,size:v.pet_size||null,notes:v.pet_notes||null},p_service_name:v.service_name,p_scheduled_at:scheduled,p_notes:v.notes||null,p_metadata:{origin:location.origin,page_path:location.pathname}});lastBooking={...v,scheduled};localStorage.removeItem("julieteBookingDraft");form.hidden=true;document.querySelector("#booking-success").classList.add("active");track("booking_completed",{appointment_id:result?.appointment_id,service:v.service_name})}catch(err){errorBox.textContent=err.message+" Seus dados continuam nesta tela para tentar novamente."}finally{submit.disabled=false;submit.textContent="Solicitar agendamento"}};
document.querySelector("#open-whatsapp").onclick=()=>{if(!lastBooking)return;const msg=`Olá, Juliete! Acabei de solicitar um agendamento pelo site para ${lastBooking.pet_name}. Serviço: ${lastBooking.service_name}. Data preferida: ${new Date(lastBooking.scheduled).toLocaleDateString("pt-BR")}, às ${lastBooking.time}. Meu nome é ${lastBooking.owner_name}. Aguardo a confirmação.`;window.open(`https://wa.me/${(cfg.whatsapp||"").replace(/\D/g,"")}?text=${encodeURIComponent(msg)}`,"_blank","noopener")};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.08});document.querySelectorAll(".reveal").forEach(x=>observer.observe(x));document.querySelector("#year").textContent=new Date().getFullYear();loadServices();track("page_view");

const baseSetStep=setStep,stepNames=["Escolha o serviço","Conte sobre o pet","Escolha data e horário","Revise e confirme"];
setStep=function(n){baseSetStep(n);document.querySelector("#step-status").textContent=`Etapa ${n} de 4`;document.querySelector("#step-name").textContent=stepNames[n-1];document.querySelector("#progress-fill").style.width=`${n*25}%`};
const baseValidStep=validStep;
validStep=function(){document.querySelectorAll(".field-invalid").forEach(x=>x.classList.remove("field-invalid"));const ok=baseValidStep();if(!ok){const field=document.querySelector(`.form-step[data-step="${step}"] :invalid`);if(field){field.classList.add("field-invalid");field.focus({preventScroll:true});field.scrollIntoView({behavior:"smooth",block:"center"});errorBox.textContent="Confira o campo destacado para continuar."}}return ok};
document.querySelector("#service-grid").addEventListener("click",e=>{if(e.target.closest("button"))return;const card=e.target.closest(".service-card");const button=card?.querySelector("[data-service]");if(button)openBooking(button.dataset.service)});
document.querySelector("#service-grid").addEventListener("keydown",e=>{if((e.key==="Enter"||e.key===" ")&&e.target.matches(".service-card")){e.preventDefault();e.target.click()}});
const enhanceCards=()=>document.querySelectorAll(".service-card").forEach(c=>{c.tabIndex=0;c.role="button";c.setAttribute("aria-label",`Agendar ${c.querySelector("h3")?.textContent||"serviço"}`)});
new MutationObserver(enhanceCards).observe(document.querySelector("#service-grid"),{childList:true});enhanceCards();
const navObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){document.querySelectorAll(".mobile-nav a").forEach(a=>a.classList.toggle("active",a.getAttribute("href")==="#"+entry.target.id))}}),{rootMargin:"-35% 0px -55% 0px"});document.querySelectorAll("main section[id]").forEach(s=>navObserver.observe(s));
const gallery=document.querySelector("#gallery"),dots=[...document.querySelectorAll(".gallery-dots i")],lightbox=document.querySelector("#lightbox");
gallery.addEventListener("scroll",()=>{const figures=[...gallery.querySelectorAll("figure")],center=gallery.scrollLeft+gallery.clientWidth/2;let active=0,distance=Infinity;figures.forEach((f,i)=>{const d=Math.abs(f.offsetLeft+f.clientWidth/2-center);if(d<distance){distance=d;active=i}});dots.forEach((d,i)=>d.classList.toggle("active",i===active))},{passive:true});
function openPhoto(figure){const img=figure.querySelector("img");lightbox.querySelector("img").src=img.currentSrc||img.src;lightbox.querySelector("img").alt=img.alt;lightbox.querySelector("p").textContent=figure.dataset.caption||"";lightbox.showModal()}
gallery.querySelectorAll("figure").forEach(f=>{f.addEventListener("click",()=>openPhoto(f));f.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();openPhoto(f)}})});lightbox.querySelector(".lightbox-close").onclick=()=>lightbox.close();lightbox.addEventListener("click",e=>{if(e.target===lightbox)lightbox.close()});
try{const draft=JSON.parse(localStorage.getItem("julieteBookingDraft")||"null");if(draft)Object.entries(draft).forEach(([name,value])=>{const field=form.elements[name];if(!field)return;if(field instanceof RadioNodeList){const radio=[...field].find(x=>x.value===value);if(radio)radio.checked=true}else if(field.type!=="checkbox")field.value=value})}catch{}

const heroVideo=document.querySelector("#hero-video"),videoFrame=document.querySelector("#video-frame"),playButton=document.querySelector("#video-play"),soundButton=document.querySelector("#video-sound"),progressFill=document.querySelector("#video-progress-fill"),dataPlay=document.querySelector("#data-play"),reducedMotion=matchMedia("(prefers-reduced-motion: reduce)").matches,saveData=navigator.connection?.saveData;
function updateVideoControls(){const paused=heroVideo.paused;playButton.querySelector("span").textContent=paused?"▶":"Ⅱ";playButton.querySelector("b").textContent=paused?"Reproduzir":"Pausar";playButton.setAttribute("aria-label",paused?"Reproduzir vídeo":"Pausar vídeo");soundButton.querySelector("b").textContent=heroVideo.muted?"Ativar som":"Desativar som";soundButton.setAttribute("aria-label",heroVideo.muted?"Ativar som":"Desativar som");soundButton.setAttribute("aria-pressed",String(!heroVideo.muted));videoFrame.classList.toggle("is-playing",!paused)}
async function playHero(){try{await heroVideo.play()}catch{}updateVideoControls()}
playButton.onclick=()=>heroVideo.paused?playHero():(heroVideo.pause(),updateVideoControls());
soundButton.onclick=()=>{heroVideo.muted=!heroVideo.muted;sessionStorage.setItem("julieteVideoSound",heroVideo.muted?"off":"on");if(heroVideo.paused)playHero();updateVideoControls()};
heroVideo.addEventListener("timeupdate",()=>{progressFill.style.width=`${heroVideo.duration?(heroVideo.currentTime/heroVideo.duration)*100:0}%`});heroVideo.addEventListener("play",updateVideoControls);heroVideo.addEventListener("pause",updateVideoControls);
const videoObserver=new IntersectionObserver(([entry])=>{if(entry.isIntersecting&&!reducedMotion&&!saveData)playHero();else if(!entry.isIntersecting)heroVideo.pause()},{threshold:.12});videoObserver.observe(heroVideo);
if(saveData){heroVideo.removeAttribute("autoplay");dataPlay.hidden=false;playButton.hidden=true;soundButton.hidden=true;dataPlay.onclick=()=>{dataPlay.hidden=true;playButton.hidden=false;soundButton.hidden=false;playHero()}}
if(reducedMotion){heroVideo.pause();updateVideoControls()}else if(!saveData)playHero();
